manifest:
  remotes:
    - name: zmkfirmware
      url_base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      # Используем стабильную версию до перехода на Zephyr 4.x
      revision: v0.1 
      import: app/west.yml
  self:
    path: config
